### PR TITLE
Basic Parallelization

### PR DESCRIPTION
**Pull request by AadityaSuri**
Parallelized, array add, array multiply and negative, very basic openMP usage

### CODE REVIEW

**Review by AadityaSuri — COMMENTED** [review]
hm

**Comment by Maharshi-Pandya** [comment]
i'm thinking of having 2 files `smolar.c` (for serial execution) and `smolar_parallel.c` with your additions residing in the later file, since i want this repository to be cloned and ran without any setup.
can you update this PR like that, it would be great and also would resolve the conflicts.
also it would be great if you can show the execution time difference between serial and parallelized code.

**Comment by AadityaSuri** [comment]
yeah I will, slighly busy this week so wont be able to get to it immediately. I was also working on adding an optimized matmul and convolution with im2col, will do it by end of next week

**Comment by AadityaSuri** [comment]
also I saw that you want to add more dtype support. I was working on that but will need to emulate generics for it i think, is there any standard you want to set for it? generics in C can get very ugly with all the macros

**Comment by AadityaSuri** [comment]
moved the simd code to smolar-simd.c, I moved the apply function implementation there too. maybe move that without the openmp pragmas to the smolar.c if you want

**Comment by Maharshi-Pandya** [comment]
thank you! maybe matmul and convolution can be added first and then after that we can talk about the support for more dtypes and structure for generics, awesome work 🫡

**Pull request merged**
